### ISSUE TITLE
Conversion Testing

### ISSUE THREAD

**Issue by puneeths19** [shrikhaparul/Ikart#11]
Need to test the code for conversion of files like csv, parquet, json, excel and xml

**Comment by puneeths19** [comment]
Completed testing for ingesting the data from flatfiles to flatfiles like csv, Json, Parquet, Excel and xml combinations. The updated code is there in release_v1.0.0 branch (Prajwal's git account).

**Comment by puneeths19** [comment]
concatenating the date to the target file name like if we mention filename followed by "%DD%-%MM%-%YYYY%" so it will give the filename and todays date. 
not only like above mentioned format we can give 
%MM%-%DD%-%YYYY%
%YYYY%-%MM%-%DD%
%DD%%MM%%YYYY%

**Comment by luke-qk** [comment]
Closing this issue as its move to Prajwal's repo
