### ISSUE TITLE
target_max_record_count field for Target of AWS, Remote and Local Servers

### ISSUE THREAD

**Issue by prasgopi** [shrikhaparul/Ikart#15]
Based on the target_max_record_count the target files needs to split into multiple files with max records in part file.
if target as 10001 records and target_max_record_count = 5000, then there will 3 target file generated
filename_part0001.xxx with 5000 records
filename_part0002.xxx with 5000 records
filename_part0003.xxx with 1 record.

**Comment by puneeths19** [comment]
Code Build is done Undergoing Testing...

**Comment by luke-qk** [comment]
Closing this issue as its move to Prajwal's repo
