### ISSUE TITLE
Getting same error while executing Job to export data

### ISSUE THREAD

**Issue by luke-qk** [shrikhaparul/Ikart#23]
Getting the same error from UI and at Terminal as well while exporting the data to Parquet, Excel and JSON formats. Attached the log
[export_data_excel_taskLog_e983b76f-c698-457e-98f4-36d91ad2804f.log](https://github.com/shrikhaparul/Ikart/files/12857535/export_data_excel_taskLog_e983b76f-c698-457e-98f4-36d91ad2804f.log)
[export_data_parquet_taskLog_ae2c79f6-30b5-4bf0-9b97-2045cb7d2772.log](https://github.com/shrikhaparul/Ikart/files/12857541/export_data_parquet_taskLog_ae2c79f6-30b5-4bf0-9b97-2045cb7d2772.log)
[export_data_json_taskLog_58758aa1-072b-4bbe-b917-e2c47facfdb2.log](https://github.com/shrikhaparul/Ikart/files/12857542/export_data_json_taskLog_58758aa1-072b-4bbe-b917-e2c47facfdb2.log)

But for the job exporting to CSV runs without any issue:
[export_data_csv_taskLog_79e35736-576b-4554-aa5a-ce02835a7fab.log](https://github.com/shrikhaparul/Ikart/files/12857554/export_data_csv_taskLog_79e35736-576b-4554-aa5a-ce02835a7fab.log)

**Comment by puneeths19** [comment]
This issue has been resolved. Why that error occurs because using of old engine code.
