### ISSUE TITLE
S3 data loading issue

### ISSUE THREAD

**Issue by ravikiran-perumandla** [shrikhaparul/Ikart#24]
while loading the data to S3 using the existing code in framework using chunks, it will load only last chunk of data in S3. 
since S3 will replace not append the data to the files

**Comment by puneeths19** [comment]
Regarding the above issue I can be able to load all chunks of data to s3 bucket so, I tested file formats like csv, parquet, json and excel it is working fine.
Need to check on xml file formats it is not generating data properly it is showing errors.

**Comment by luke-qk** [comment]
Closing this issue as its move to Prajwal's repo
