### ISSUE TITLE
Header and Skip header row to work as one.

### ISSUE THREAD

**Issue by prasgopi** [shrikhaparul/Ikart#6]
1) if the skip_header = 1, then this considered as Header record.
2) if the skip_header = 0, then there is no header records. Even if the file has header records, then header is considered as record.
3) if the skip_header > 1, the 1 record is considered as Header record, then skip_header - 1 are skipped and rest of records are loaded.

Currently this is not working as above.

**Comment by madhushree211999** [comment]
skip_header and skip_footer is working , uploded in development branch (csv_read)

**Comment by luke-qk** [comment]
Closing this issue as its move to Prajwal's repo
