### ISSUE TITLE
Process multiple files in source folder

### ISSUE THREAD

**Issue by prasgopi** [shrikhaparul/Ikart#7]
Code should be able to ingest the multiple files in folder of same structure like  product_part_0*.csv, etc...

Based on the example all files qualify the file name (product_part_01/02/03....csv) needs to processed.

**Comment by puneeths19** [comment]
for the above raised issue i am able to resolve the issue for multiple csv file reading from local server.

**Comment by prasgopi** [comment]
Not tested for multiple Parquet file.

**Comment by puneeths19** [comment]
Multiple parquet file processing is working the code is there in development branch.

**Comment by puneeths19** [comment]
For the above issue the below mentioned file listings or file name would work:
-- *.extension  (extension can be *.csv, *.dat, *.txt, *.json, *.parquet, *.excel, *.xml)

File name field (file_name) can be left as blank (or null) then the job will pick-up/process all files as long as the are of same structure and extension.
